FROM mcr-proxy.kontur.host/dotnet/sdk:8.0

RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    ca-certificates \
    curl \
    && curl -sL https://deb.nodesource.com/setup_16.x | bash - \
    && apt-get install -y nodejs \
    && npm config set registry https://nexus.kontur.host/repository/kontur-npm-group/ --global \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
RUN dotnet build Source/Kontur.BigLibrary.Tests.UI.PW/Kontur.BigLibrary.Tests.UI.PW.csproj -c Debug
RUN pwsh "Source/Kontur.BigLibrary.Tests.UI.PW/bin/Debug/net8.0/playwright.ps1" install --with-deps