stages:
  - build
  - tests

variables:
  IMAGE_VERSION: $CI_COMMIT_SHORT_SHA
  DOTNET_NPM_IMAGE_NAME: dotnet-npm
  PLAYWRIGHT_IMAGE_NAME: playwright-chrome
  UI_TESTS_LOCATION: Source/Kontur.BigLibrary.Tests.UI.PW/Kontur.BigLibrary.Tests.UI.PW.csproj
  FLAKY_TESTS_CATEGORY: "Flaky"
  CI_DEBUG_TRACE: "false" # подробные логи при запуске джоб
  HEADLESS: "true" # запускаем браузерные тесты в режиме headless

'Build library':
  stage: build
  image: $REGISTRY_FOLDER/$DOTNET_NPM_IMAGE_NAME:latest
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - Build/Kontur.BigLibrary.Service/
    expire_in: 1 week
  needs: [ ]
  extends:
    - .browser_tests_rules

'UI tests':
  stage: tests
  extends: 
  - .ui_tests_template
  - .browser_tests_rules
  script:
    - dotnet test $UI_TESTS_LOCATION --filter "Category!=$FLAKY_TESTS_CATEGORY" --logger "junit;LogFileName=UITests.xml" --results-directory TestResults
  allow_failure: false
  artifacts:
    when: always
    expire_in: "15 days"
    reports:
      junit: TestResults/UITests.xml
    paths:
      - "TestResults/UITests.xml"
      - Artifacts

'Flaky UI-tests':
  stage: tests
  extends:
    - .ui_tests_template
    - .browser_tests_rules
  script:
    - dotnet test $UI_TESTS_LOCATION --filter "Category=$FLAKY_TESTS_CATEGORY" --logger "junit;LogFileName=FlakyUITests.xml" --results-directory TestResults
  allow_failure: true
  artifacts:
    when: always
    expire_in: "15 days"
    reports:
      junit: TestResults/FlakyUITests.xml
    paths:
      - "TestResults/FlakyUITests.xml"
      - Artifacts


# Мы создали этот шаблон, т.к. он будет использоваться минимум дважды: 
# Для запуска всех UI-тестов и только для определенной категории 
.ui_tests_template:
  stage: tests
  image: $REGISTRY_FOLDER/$PLAYWRIGHT_IMAGE_NAME:latest
  variables:
    FIIT_SERVICE_URL: "http://localhost:5000"
  before_script: # Ставим PW, запускаем сервис и дожидаемся его готовности
    - cd Build/Kontur.BigLibrary.Service
    - chmod +x Kontur.BigLibrary.Service
    - ./Kontur.BigLibrary.Service &
    - cd ../..
    - |
      while ! curl -s -o /dev/null -w "%{http_code}" http://localhost:5000 | grep -q "200"; do
          echo 'Waiting for fiit-service...'; 
          sleep 10; 
      done 
  after_script: # выгружаем скриншоты, которые сохраняются в папку bin/Debug/net8.0/TestResults
    - mkdir -p Artifacts
    - |
      if [ -d "Source/Kontur.BigLibrary.Tests.UI/bin/Debug/net8.0/TestResults" ]; then
        cp -r Source/Kontur.BigLibrary.Tests.UI/bin/Debug/net8.0/TestResults/* Artifacts/
      else
        echo "Artifacts directory not found"
      fi
  needs:
    - job: 'Build library'
      artifacts: true
      
.browser_tests_rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
    - when: never